import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

// Safari는 weight을 넣어주지 않으면 폰트를 가져오지 못함.
const montserrat = Montserrat({ 
  subsets: ["latin"], 
  display: "swap",
  variable : "--font-montserrat",
  weight : "700" });

export const metadata: Metadata = {
  title: "Play Barcode",
  description: "Generated by create next app",
}; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
          {children}
      </body>
    </html>
  );
}